name: 'flattenRepository'
description: 'Flatten terraform files to target repo'
inputs:
  DEPLOY_FOLDER:
    description: 'DEPLOY FOLDER'
    required: true
    default: '$(pwd)/'
  working-directory:
    description: 'Working directory'
    required: true
    default: '$(pwd)/iac'
outputs:
  random-number: 
    description: "Rando m number"
#    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps: 
    - run: |
        git config --global user.name $GITHUB_ACTOR 
        chmod +x ${{ github.action_path }}/flatten.sh
      shell: bash
    - run: ${{ github.action_path }}/flatten.sh ${{ inputs.DEPLOY_FOLDER }} ${{ inputs.working-directory }}
      shell: bash    
