name: 'flattenRepository'
description: 'Flatten terraform files to target repo'
inputs:
  DEPLOY_FOLDER:
    description: 'DEPLOY FOLDER'
    required: true
    default: '$(pwd)/configfolder'
  working-directory:
    description: 'Working directory'
    required: true
    default: '$(pwd)/'
outputs:
  ENV_FULL_PATH: 
    description: "Rando m number"
  
runs:
  using: "composite"
  steps: 
    - run: |
        git config --global user.name $GITHUB_ACTOR 
        chmod +x ${{ github.action_path }}/flatten.sh
      shell: bash
    - run: ${{ github.action_path }}/flatten.sh ${{ inputs.DEPLOY_FOLDER }} ${{ inputs.working-directory }}
      shell: bash    
