name: 'flattenRepository'
description: 'Flatten terraform files to target repo'
inputs:
  DEPLOY_FOLDER:
    description: 'DEPLOY FOLDER'
    required: true
    default: '$(pwd)/'
  working-directory:
    description: 'Working directory'
    required: true
    default: code
outputs:
  random-number: 
    description: "Rando m number"
#    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps: 
    - run: |
        pwd
        ls -lsa configrepo
        printenv
        git config --global user.name $GITHUB_ACTOR 
        echo "action_path  ${{ github.action_path }}"
        chmod +x ${{ github.action_path }}/flatten.sh
        echo "::set-output name=DEPLOY_FOLDER::$(pwd)/configrepo"
        echo "::set-output name=working-directory::$(pwd)/working_folder"
      shell: bash
#    - id: random-number-generator
#      run: echo "::set-output name=random-id::$(echo $RANDOM)"
#      shell: bash
    - run: ${{ github.action_path }}/flatten.sh
      shell: bash    
